name: NPM BUILD

on:
  push:
    paths: 
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: cd src; npm install vue-cli; npm run build
      
